import { Project } from "@/types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Brick Breaker Game",
    description: "Collaborative arcade game project featuring dynamic ball physics, collision detection, and progressive levels. Built with C++ and SFML graphics library using OOP principles. Implemented game state management, particle effects, and score tracking.",
    img: "/images/projects/p1.webp",
    technologies: ["C++", "SFML"],
    category: "group",
    githubURL: "https://github.com/chyroshan066/brick-breaker",
  },
  {
    id: 2,
    title: "Jasmina",
    description: "",
    img: "/images/p2.png",
    technologies: [],
    category: "client",
    liveURL: "http://localhost:3000",
    githubURL: "http://localhost:3000",
  },
  {
    id: 3,
    title: "d.tampe",
    description: "",
    img: "/images/p3.png",
    technologies: [],
    category: "personal",
    liveURL: "",
    githubURL: "http://localhost:3000",
  },
  {
    id: 4,
    title: "Blimp.gr",
    img: "/images/p4.png",
    technologies: [],
    category: "client",
    liveURL: "http://localhost:3000",
    githubURL: "",
  },
  {
    id: 5,
    title: "Hawk Style Design",
    description: "",
    img: "/images/p5.png",
    technologies: [],
    category: "personal",
    liveURL: "",
    githubURL: "",
  },
  {
    id: 6,
    title: "Lewis",
    description: "",
    img: "/images/p6.png",
    technologies: [],
    category: "client",
    liveURL: "",
    githubURL: "",
  },
  {
    id: 7,
    title: "Brick Breaker Game",
    description: "Collaborative arcade game project featuring dynamic ball physics, collision detection, and progressive levels. Built with C++ and SFML graphics library using OOP principles. Implemented game state management, particle effects, and score tracking.",
    img: "/images/projects/p1.webp",
    technologies: ["C++", "SFML"],
    category: "group",
    githubURL: "https://github.com/chyroshan066/brick-breaker",
  },
];

export const projectsMetadata = {
  total: projects.length,
  categories: [...new Set(projects.map(p => p.category))],
  technologies: [...new Set(projects.flatMap(p => p.technologies))],
} as const;