import { Project } from "@/types";

export const projects: Project[] = [
  {
    id: 1,
    title: "Gurung BBQ",
    description: "Professional restaurant website designed and developed as a solo project for Gurung BBQ. Features responsive design, interactive menu system, and seamless user experience to showcase authentic cuisine and enhance online presence. Built with modern web technologies focusing on performance and accessibility.",
    img: "/images/projects/p2.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form"],
    category: "client",
    liveURL: "https://www.gurungbbq.com/",
    githubURL: "https://github.com/chyroshan066/gurung-bbq",
  },
  {
    id: 2,
    title: "Sewaro Tattoo",
    description: "Professional tattoo studio website designed and developed as a solo project for Sewaro Tattoo. Features responsive design, dynamic portfolio galleries, and intuitive booking system to showcase artistic excellence and enhance client engagement. Built with modern web technologies focusing on visual impact and seamless user experience.",
    img: "/images/projects/p3.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form", "Bootstrap", "Swiper.js"],
    category: "client",
    liveURL: "https://www.sewarotattoo.com/",
    githubURL: "https://github.com/chyroshan066/sewaro-tattoo",
  },
  {
    id: 3,
    title: "Absolute Professional Spa & Salon",
    description: "Professional spa and salon website designed and developed as a solo project for Absolute Professional Spa & Salon. Features responsive design, treatment showcase system, and seamless appointment booking to highlight wellness services across three locations in Nepal and India. Built with modern web technologies focusing on performance, accessibility, and user experience.",
    img: "/images/projects/p4.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form", "Bootstrap"],
    category: "client",
    liveURL: "https://www.absoluteprofessionalspa.com.np/",
    githubURL: "https://github.com/chyroshan066/absolute-professional-spa-and-salon",
  },
  {
    id: 4,
    title: "Pradhan Dental",
    description: "Professional dental clinic website designed and developed as a solo project for Pradhan Dental. Features responsive design, comprehensive service showcase, and seamless appointment booking to present dental treatments and enhance patient engagement. Built with modern web technologies focusing on performance, accessibility, and trust-building user experience.",
    img: "/images/projects/p5.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form"],
    category: "client",
    liveURL: "https://www.pradhandental.com/",
    githubURL: "https://github.com/chyroshan066/pradhan-dental",
  },
  {
    id: 5,
    title: "Purwanchal Vet Pharma",
    description: "Professional veterinary clinic website designed and developed as a solo project for Purwanchal Vet Pharma. Features responsive design, comprehensive service catalog, and seamless appointment booking to showcase veterinary care for pets and livestock. Built with modern web technologies focusing on performance, accessibility, and compassionate user experience.",
    img: "/images/projects/p6.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form", "Bootstrap"],
    category: "client",
    liveURL: "https://www.purwanchalvetpharma.com.np/",
    githubURL: "https://github.com/chyroshan066/purwanchal-vet-pharma",
  },
  {
    id: 6,
    title: "Pathivara Baby Store",
    description: "Professional baby store website designed and developed as a solo project for Pathivara Baby Store. Features responsive design, interactive product catalog, and seamless shopping experience to showcase baby products and enhance online retail presence. Built with modern web technologies focusing on performance, accessibility, and parent-friendly navigation.",
    img: "/images/projects/p7.webp",
    technologies: ["Next.js", "Tailwind CSS", "TypeScript", "React Hook Form", "Bootstrap", "Swiper.js"],
    category: "client",
    liveURL: "https://pathivara-baby-store.vercel.app/",
    githubURL: "https://github.com/chyroshan066/pathivara-baby-store",
  },
{
    id: 7,
    title: "Brick Breaker Game",
    description: "Collaborative arcade game project featuring dynamic ball physics, collision detection, and progressive levels. Built with C++ and SFML graphics library using OOP principles. Implemented game state management, particle effects, and score tracking.",
    img: "/images/projects/p1.webp",
    technologies: ["C++", "SFML"],
    category: "group",
    githubURL: "https://github.com/chyroshan066/brick-breaker",
  },
];

export const projectsMetadata = {
  total: projects.length,
  categories: [...new Set(projects.map(p => p.category))],
  technologies: [...new Set(projects.flatMap(p => p.technologies))],
} as const;